{{- if .Values.backups.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-pgbackrest-secret" (include "pg-cluster.fullname" .) }}
type: Opaque
stringData:
  pgbackrest.conf: |
    [global]
    repo2-s3-key={{ .Values.backups.s3.user }}
    repo2-s3-key-secret={{ .Values.backups.s3.secret }}
{{- end }}
