{{- if .Values.pmm_server_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-pmm-secret" (include "pg-cluster.fullname" .) }}
type: Opaque
stringData:
  PMM_SERVER_TOKEN: {{ .Values.pmm_server_token | quote }}
{{- end }}
